# Translations template for barbican.
# Copyright (C) 2015 ORGANIZATION
# This file is distributed under the same license as the barbican project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2015.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: barbican 2015.1.dev66\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2015-02-21 06:07+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"

#: barbican/api/__init__.py:62
msgid "Read Error"
msgstr ""

#: barbican/api/__init__.py:72
msgid "Malformed JSON"
msgstr ""

#: barbican/api/__init__.py:106
msgid ""
"{operation} attempt not allowed - please review your user/project "
"privileges"
msgstr ""

#: barbican/api/__init__.py:116
msgid "{operation} failure seen - please contact site administrator."
msgstr ""

#: barbican/api/__init__.py:120
msgid "{operation} issue seen - {reason}."
msgstr ""

#: barbican/api/controllers/__init__.py:91
msgid "System"
msgstr ""

#: barbican/api/controllers/__init__.py:123
msgid "Unexpected content type: {type}.  Expected content types are: {expected}"
msgstr ""

#: barbican/api/controllers/consumers.py:31
msgid "Not Found. Sorry but your consumer is in another castle."
msgstr ""

#: barbican/api/controllers/consumers.py:49
msgid "ContainerConsumer retrieval"
msgstr ""

#: barbican/api/controllers/consumers.py:87
msgid "ContainerConsumers(s) retrieval"
msgstr ""

#: barbican/api/controllers/consumers.py:126
msgid "ContainerConsumer creation"
msgstr ""

#: barbican/api/controllers/consumers.py:155
msgid "ContainerConsumer deletion"
msgstr ""

#: barbican/api/controllers/containers.py:32
msgid "Not Found. Sorry but your container is in another castle."
msgstr ""

#: barbican/api/controllers/containers.py:56
msgid "Container retrieval"
msgstr ""

#: barbican/api/controllers/containers.py:76
msgid "Container deletion"
msgstr ""

#: barbican/api/controllers/containers.py:123
msgid "Containers(s) retrieval"
msgstr ""

#: barbican/api/controllers/containers.py:161
msgid "Container creation"
msgstr ""

#: barbican/api/controllers/containers.py:186
msgid "Secret provided for '{secret_name}' doesn't exist."
msgstr ""

#: barbican/api/controllers/orders.py:31
msgid "Not Found. Sorry but your order is in another castle."
msgstr ""

#: barbican/api/controllers/orders.py:37
msgid "Secret metadata expected but not received."
msgstr ""

#: barbican/api/controllers/orders.py:42
msgid "Order update is not supported."
msgstr ""

#: barbican/api/controllers/orders.py:47
msgid "Updates are not supported for order type {0}."
msgstr ""

#: barbican/api/controllers/orders.py:53
msgid "Only PENDING orders can be updated. Order is in the{0} state."
msgstr ""

#: barbican/api/controllers/orders.py:59
msgid "Cannot modify order type."
msgstr ""

#: barbican/api/controllers/orders.py:78
msgid "Order retrieval"
msgstr ""

#: barbican/api/controllers/orders.py:84 barbican/api/controllers/orders.py:177
msgid "Order update"
msgstr ""

#: barbican/api/controllers/orders.py:108
msgid "Order deletion"
msgstr ""

#: barbican/api/controllers/orders.py:150
msgid "Order(s) retrieval"
msgstr ""

#: barbican/api/controllers/orders.py:183
msgid "Order creation"
msgstr ""

#: barbican/api/controllers/secrets.py:44
msgid "Not Found. Sorry but your secret is in another castle."
msgstr ""

#: barbican/api/controllers/secrets.py:50
msgid "Secret already has data, cannot modify it."
msgstr ""

#: barbican/api/controllers/secrets.py:59
msgid ""
"Transport key wrapped session key has been provided to wrap secrets for "
"retrieval, but the transport key id has not been provided."
msgstr ""

#: barbican/api/controllers/secrets.py:89
msgid "Secret retrieval"
msgstr ""

#: barbican/api/controllers/secrets.py:152
msgid "Secret update"
msgstr ""

#: barbican/api/controllers/secrets.py:162
msgid "Content-Type of '{content_type}' is not supported for PUT."
msgstr ""

#: barbican/api/controllers/secrets.py:189
msgid "Secret deletion"
msgstr ""

#: barbican/api/controllers/secrets.py:241
msgid "Secret(s) retrieval"
msgstr ""

#: barbican/api/controllers/secrets.py:292
msgid "Secret creation"
msgstr ""

#: barbican/api/controllers/transportkeys.py:34
msgid "Not Found. Transport Key not found."
msgstr ""

#: barbican/api/controllers/transportkeys.py:50
msgid "Transport Key retrieval"
msgstr ""

#: barbican/api/controllers/transportkeys.py:62
msgid "Transport Key deletion"
msgstr ""

#: barbican/api/controllers/transportkeys.py:94
msgid "Transport Key(s) retrieval"
msgstr ""

#: barbican/api/controllers/transportkeys.py:132
msgid "Transport Key Creation"
msgstr ""

#: barbican/api/controllers/versions.py:33
msgid "Version retrieval"
msgstr ""

#: barbican/api/middleware/context.py:30
msgid ""
"When true, this option sets the owner of an image to be the project. "
"Otherwise, the owner of the  image will be the authenticated user issuing"
" the request."
msgstr ""

#: barbican/api/middleware/context.py:35
msgid "Role used to identify an authenticated user as administrator."
msgstr ""

#: barbican/api/middleware/context.py:38
msgid ""
"Allow unauthenticated users to access the API with read-only privileges. "
"This only applies when using ContextMiddleware."
msgstr ""

#: barbican/api/middleware/context.py:117
msgid "Problem processing X-Service-Catalog"
msgstr ""

#: barbican/api/middleware/context.py:142
msgid "Missing X-Project-Id"
msgstr ""

#: barbican/common/exception.py:39
msgid "An unknown exception occurred"
msgstr ""

#: barbican/common/exception.py:67
msgid "failure seen - please contact site administrator."
msgstr ""

#: barbican/common/exception.py:72
msgid "Missing required argument."
msgstr ""

#: barbican/common/exception.py:76
#, python-format
msgid "Missing required credential: %(required)s"
msgstr ""

#: barbican/common/exception.py:80
#, python-format
msgid "Missing required metadata field for %(required)s"
msgstr ""

#: barbican/common/exception.py:84
msgid "Invalid subject DN: %(subject_dn)"
msgstr ""

#: barbican/common/exception.py:88
msgid "Invalid container: %(reason)"
msgstr ""

#: barbican/common/exception.py:92
msgid "Invalid extensions data."
msgstr ""

#: barbican/common/exception.py:96
msgid "Invalid CMC Data"
msgstr ""

#: barbican/common/exception.py:100
msgid "Invalid PKCS10 Data"
msgstr ""

#: barbican/common/exception.py:104
msgid "Invalid Certificate Request Type"
msgstr ""

#: barbican/common/exception.py:108
#, python-format
msgid ""
"Incorrect auth strategy, expected \"%(expected)s\" but received "
"\"%(received)s\""
msgstr ""

#: barbican/common/exception.py:113
msgid "An object with the specified identifier was not found."
msgstr ""

#: barbican/common/exception.py:117
#, python-format
msgid "Unknown scheme '%(scheme)s' found in URI"
msgstr ""

#: barbican/common/exception.py:121
msgid "The Store URI was malformed."
msgstr ""

#: barbican/common/exception.py:125
msgid "An object with the same identifier already exists."
msgstr ""

#: barbican/common/exception.py:129
msgid "There is not enough disk space on the image storage media."
msgstr ""

#: barbican/common/exception.py:133
msgid "Permission to write image storage media denied."
msgstr ""

#: barbican/common/exception.py:137
#, python-format
msgid "Connect error/bad request to Auth service at URL %(url)s."
msgstr ""

#: barbican/common/exception.py:141
#, python-format
msgid "Auth service at URL %(url)s not found."
msgstr ""

#: barbican/common/exception.py:145
msgid "Authorization failed."
msgstr ""

#: barbican/common/exception.py:149
msgid "You are not authenticated."
msgstr ""

#: barbican/common/exception.py:153 barbican/common/exception.py:161
#: barbican/common/exception.py:170
msgid "You are not authorized to complete this action."
msgstr ""

#: barbican/common/exception.py:157
msgid "Operation is not supported."
msgstr ""

#: barbican/common/exception.py:165
#, python-format
msgid "Image %(image_id)s is protected and cannot be deleted."
msgstr ""

#: barbican/common/exception.py:174
msgid "Data supplied was not valid."
msgstr ""

#: barbican/common/exception.py:178
msgid "No data supplied to process."
msgstr ""

#: barbican/common/exception.py:184
msgid "Sort key supplied was not valid."
msgstr ""

#: barbican/common/exception.py:188
msgid "Unable to filter using the specified range."
msgstr ""

#: barbican/common/exception.py:192
#, python-format
msgid "Attribute '%(property)s' is read-only."
msgstr ""

#: barbican/common/exception.py:196
#, python-format
msgid "Attribute '%(property)s' is reserved."
msgstr ""

#: barbican/common/exception.py:200
#, python-format
msgid "Redirecting to %(uri)s for authorization."
msgstr ""

#: barbican/common/exception.py:204
msgid "There was an error migrating the database."
msgstr ""

#: barbican/common/exception.py:208
msgid "There was an error connecting to a server"
msgstr ""

#: barbican/common/exception.py:212
msgid "There was an error configuring the client."
msgstr ""

#: barbican/common/exception.py:216
#, python-format
msgid ""
"The request returned a 302 Multiple Choices. This generally means that "
"you have not included a version indicator in a request URI.\n"
"\n"
"The body of response returned:\n"
"%(body)s"
msgstr ""

#: barbican/common/exception.py:223
#, python-format
msgid ""
"The request returned a 413 Request Entity Too Large. This generally means"
" that rate limiting or a quota threshold was breached.\n"
"\n"
"The response body:\n"
"%(body)s"
msgstr ""

#: barbican/common/exception.py:226
msgid "Provided information too large to process"
msgstr ""

#: barbican/common/exception.py:236
msgid ""
"The request returned 503 Service Unavilable. This generally occurs on "
"service overload or other transient outage."
msgstr ""

#: barbican/common/exception.py:247
msgid "The request returned 500 Internal Server Error."
msgstr ""

#: barbican/common/exception.py:251
#, python-format
msgid ""
"The request returned an unexpected status: %(status)s.\n"
"\n"
"The response body:\n"
"%(body)s"
msgstr ""

#: barbican/common/exception.py:256
#, python-format
msgid "Invalid content type %(content_type)s"
msgstr ""

#: barbican/common/exception.py:260
#, python-format
msgid "Invalid content encoding %(content_encoding)s"
msgstr ""

#: barbican/common/exception.py:264
msgid "Error while attempting to decode payload."
msgstr ""

#: barbican/common/exception.py:268
#, python-format
msgid "Registry was not configured correctly on API server. Reason: %(reason)s"
msgstr ""

#: barbican/common/exception.py:273
#, python-format
msgid "Store %(store_name)s could not be configured correctly. Reason: %(reason)s"
msgstr ""

#: barbican/common/exception.py:278
#, python-format
msgid ""
"Driver %(driver_name)s could not be configured correctly. Reason: "
"%(reason)s"
msgstr ""

#: barbican/common/exception.py:283
msgid "Deleting images from this store is not supported."
msgstr ""

#: barbican/common/exception.py:287
msgid "Configuration for store failed. Adding images to this store is disabled."
msgstr ""

#: barbican/common/exception.py:292
#, python-format
msgid "'%(strategy)s' is not an available notifier strategy."
msgstr ""

#: barbican/common/exception.py:296
#, python-format
msgid "Maximum redirects (%(redirects)s) was exceeded."
msgstr ""

#: barbican/common/exception.py:300
msgid "Received invalid HTTP redirect."
msgstr ""

#: barbican/common/exception.py:304
msgid "Response from Keystone does not contain a Barbican endpoint."
msgstr ""

#: barbican/common/exception.py:309
#, python-format
msgid ""
"Multiple 'image' service matches for region %(region)s. This generally "
"means that a region is required and you have not supplied one."
msgstr ""

#: barbican/common/exception.py:315
#, python-format
msgid "Server worker creation failed: %(reason)s."
msgstr ""

#: barbican/common/exception.py:319
#, python-format
msgid "Unable to load schema: %(reason)s"
msgstr ""

#: barbican/common/exception.py:327
msgid "Failed to validate JSON information: "
msgstr ""

#: barbican/common/exception.py:328
msgid "Provided object does not match schema '{schema}': {reason}"
msgstr ""

#: barbican/common/exception.py:336
#, python-format
msgid ""
"No support for value set on field '%(field)s' on schema '%(schema)s': "
"%(reason)s"
msgstr ""

#: barbican/common/exception.py:338
msgid "Provided field value is not supported"
msgstr ""

#: barbican/common/exception.py:347
#, python-format
msgid ""
"Feature not implemented for value set on field '%(field)s' on schema "
"'%(schema)s': %(reason)s"
msgstr ""

#: barbican/common/exception.py:356
#, python-format
msgid "Provided header feature is unsupported: %(feature)s"
msgstr ""

#: barbican/common/exception.py:360
msgid ""
"The image cannot be deleted because it is in use through the backend "
"store outside of Barbican."
msgstr ""

#: barbican/common/exception.py:365
msgid "The provided image is too large."
msgstr ""

#: barbican/common/exception.py:369
#, python-format
msgid ""
"Container %(container_id) does not exist for stored key certificate "
"generation."
msgstr ""

#: barbican/common/exception.py:374
#, python-format
msgid ""
"Container %(container_id) does not reference a private key needed for "
"stored key certificate generation."
msgstr ""

#: barbican/common/exception.py:379
msgid "The provided UUID in the URI (%(uuid_string)) is malformed."
msgstr ""

#: barbican/common/exception.py:381
msgid "The provided UUID in the URI is malformed."
msgstr ""

#: barbican/common/utils.py:113
msgid "Cannot generate a fullname for a null instance"
msgstr ""

#: barbican/common/validators.py:83
msgid "{schema_name}' within '{parent_schema_name}"
msgstr ""

#: barbican/common/validators.py:167
msgid "If 'payload' specified, must be non empty"
msgstr ""

#: barbican/common/validators.py:173
msgid "payload must be provided when payload_content_type is specified"
msgstr ""

#: barbican/common/validators.py:202 barbican/common/validators.py:491
msgid "Invalid date for 'expiration'"
msgstr ""

#: barbican/common/validators.py:216
msgid "'expiration' is before current time"
msgstr ""

#: barbican/common/validators.py:229
msgid "If 'payload' is supplied, 'payload_content_type' must also be supplied."
msgstr ""

#: barbican/common/validators.py:240
msgid ""
"payload_content_encoding must be specified when payload_content_type is "
"application/octet-stream."
msgstr ""

#: barbican/common/validators.py:248
msgid ""
"payload_content_encoding must not be specified when payload_content_type "
"is text/plain"
msgstr ""

#: barbican/common/validators.py:257
msgid "payload_content_type is not one of {supported}"
msgstr ""

#: barbican/common/validators.py:328
msgid "'payload' not allowed for key type order"
msgstr ""

#: barbican/common/validators.py:347
msgid "Only 'application/octet-stream' supported"
msgstr ""

#: barbican/common/validators.py:474
msgid "'algorithm' is required field for {0} type order"
msgstr ""

#: barbican/common/validators.py:503
msgid "Must have non-zero positive bit_length to generate secret"
msgstr ""

#: barbican/common/validators.py:511
msgid "Must be a positive integer that is a multiple of 8"
msgstr ""

#: barbican/common/validators.py:519
msgid "Feature not implemented for '{0}' order type"
msgstr ""

#: barbican/common/validators.py:591
msgid "Duplicate reference names are not allowed"
msgstr ""

#: barbican/common/validators.py:603
msgid "Duplicate secret ids are not allowed"
msgstr ""

#: barbican/common/validators.py:621
msgid ""
"only 'private_key', 'public_key' and 'private_key_passphrase' reference "
"names are allowed for RSA type"
msgstr ""

#: barbican/common/validators.py:629
msgid ""
"The minimum required reference names are 'public_key' and'private_key' "
"for RSA type"
msgstr ""

#: barbican/common/validators.py:642
msgid ""
"only 'private_key', 'certificate' , 'private_key_passphrase',  or "
"'intermediates' reference names are allowed for Certificate type"
msgstr ""

#: barbican/common/validators.py:650
msgid "The minimum required reference name is 'certificate' for Certificate type"
msgstr ""

#: barbican/common/validators.py:696
msgid "plugin_name must be provided"
msgstr ""

#: barbican/common/validators.py:703
msgid "transport_key must be provided"
msgstr ""

#: barbican/model/models.py:761
msgid "Must supply Non-None {0} argument for CertificateAuthority entry."
msgstr ""

#: barbican/model/models.py:827
msgid "Must supply non-None {0} argument for CertificateAuthorityMetadatum entry."
msgstr ""

#: barbican/model/models.py:872
msgid "Must supply non-None {0} argument for ProjectCertificateAuthority entry."
msgstr ""

#: barbican/model/models.py:919
msgid "Must supply non-None {0} argument for PreferredCertificateAuthority entry."
msgstr ""

#: barbican/model/repositories.py:177
msgid "No SQL connection configured"
msgstr ""

#: barbican/model/repositories.py:191
msgid ""
"Error configuring registry database with supplied sql_connection. Got "
"error: {error}"
msgstr ""

#: barbican/model/repositories.py:419
msgid "Must supply non-None {entity_name}."
msgstr ""

#: barbican/model/repositories.py:425
msgid "Must supply {entity_name} with id=None (i.e. new entity)."
msgstr ""

#: barbican/model/repositories.py:503
msgid "{entity_name} status is required."
msgstr ""

#: barbican/model/repositories.py:508
msgid "Invalid status '{status}' for {entity_name}."
msgstr ""

#: barbican/model/repositories.py:528
msgid "{entity_name} is missing query build method for get project entities."
msgstr ""

#: barbican/model/repositories.py:580
#, python-format
msgid "Error deleting project entities for project_id=%s"
msgstr ""

#: barbican/model/repositories.py:612
msgid "No {entity_name} found with keystone-ID {id}"
msgstr ""

#: barbican/model/repositories.py:809
msgid "Tried to register crypto plugin with null or empty name."
msgstr ""

#: barbican/model/repositories.py:1147
msgid "Could not find {entity_name}"
msgstr ""

#: barbican/model/repositories.py:1331
msgid "No {entity} found with ID {id}"
msgstr ""

#: barbican/model/repositories.py:1337
msgid "Entity ID {entity_id} not found"
msgstr ""

#: barbican/model/repositories.py:1343
msgid "No entities of type {entity_name} found"
msgstr ""

#: barbican/model/repositories.py:1349
msgid "Entity '{entity_name}' already exists"
msgstr ""

#: barbican/openstack/common/gettextutils.py:305
msgid "Message objects do not support addition."
msgstr ""

#: barbican/openstack/common/gettextutils.py:315
msgid ""
"Message objects do not support str() because they may contain non-ascii "
"characters. Please use unicode() or translate() instead."
msgstr ""

#: barbican/openstack/common/policy.py:111
msgid "The JSON file that defines policies."
msgstr ""

#: barbican/openstack/common/policy.py:114
msgid "Default rule. Enforced when a requested rule is not found."
msgstr ""

#: barbican/openstack/common/policy.py:118
msgid ""
"Directories where policy configuration files are stored. They can be "
"relative to any directory in the search path defined by the config_dir "
"option, or absolute paths. The file defined by policy_file must exist for"
" these directories to be searched."
msgstr ""

#: barbican/openstack/common/policy.py:142
#, python-format
msgid "Policy doesn't allow %s to be performed."
msgstr ""

#: barbican/openstack/common/policy.py:239
#, python-format
msgid "Rules must be an instance of dict or Rules, got %s instead"
msgstr ""

#: barbican/openstack/common/processutils.py:90
#, python-format
msgid "Got unknown keyword args to utils.execute: %r"
msgstr ""

#: barbican/openstack/common/processutils.py:99
#, python-format
msgid "Running cmd (subprocess): %s"
msgstr ""

#: barbican/openstack/common/processutils.py:114
#, python-format
msgid "Result was %s"
msgstr ""

#: barbican/openstack/common/processutils.py:128
#, python-format
msgid "%r failed. Retrying."
msgstr ""

#: barbican/openstack/common/sslutils.py:52
#, python-format
msgid "Unable to find cert_file : %s"
msgstr ""

#: barbican/openstack/common/sslutils.py:55
#, python-format
msgid "Unable to find ca_file : %s"
msgstr ""

#: barbican/openstack/common/sslutils.py:58
#, python-format
msgid "Unable to find key_file : %s"
msgstr ""

#: barbican/openstack/common/sslutils.py:61
msgid ""
"When running server in SSL mode, you must specify both a cert_file and "
"key_file option value in your configuration file"
msgstr ""

#: barbican/openstack/common/sslutils.py:100
#, python-format
msgid "Invalid SSL version : %s"
msgstr ""

#: barbican/openstack/common/strutils.py:92
#, python-format
msgid "Unrecognized value '%(val)s', acceptable values are: %(acceptable)s"
msgstr ""

#: barbican/openstack/common/strutils.py:197
#, python-format
msgid "Invalid unit system: \"%s\""
msgstr ""

#: barbican/openstack/common/strutils.py:206
#, python-format
msgid "Invalid string format: %s"
msgstr ""

#: barbican/openstack/common/crypto/utils.py:29
msgid "An unknown error occurred in crypto utils."
msgstr ""

#: barbican/openstack/common/crypto/utils.py:36
#, python-format
msgid "Block size of %(given)d is too big, max = %(maximum)d"
msgstr ""

#: barbican/openstack/common/crypto/utils.py:45
#, python-format
msgid "Length of %(given)d is too long, max = %(maximum)d"
msgstr ""

#: barbican/plugin/dogtag.py:44
msgid "Path to PEM file for authentication"
msgstr ""

#: barbican/plugin/dogtag.py:47
msgid "Hostname for the Dogtag instance"
msgstr ""

#: barbican/plugin/dogtag.py:50
msgid "Port for the Dogtag instance"
msgstr ""

#: barbican/plugin/dogtag.py:52
msgid "Path to the NSS certificate database"
msgstr ""

#: barbican/plugin/dogtag.py:54
msgid "Password for NSS certificate database"
msgstr ""

#: barbican/plugin/dogtag.py:56
msgid "Profile for simple CMC requests"
msgstr ""

#: barbican/plugin/dogtag.py:70
msgid "nss_password is required"
msgstr ""

#: barbican/plugin/dogtag.py:85
msgid "pem_path is required"
msgstr ""

#: barbican/plugin/dogtag.py:96
msgid "Invalid algorithm passed in"
msgstr ""

#: barbican/plugin/dogtag.py:100
msgid "Operation not supported by Dogtag Plugin"
msgstr ""

#: barbican/plugin/dogtag.py:359
msgid ""
"Passphrase encryption is not supported for symmetric key generating "
"algorithms."
msgstr ""

#: barbican/plugin/dogtag.py:391
msgid "Passphrase encryption is not supported for DSA algorithm"
msgstr ""

#: barbican/plugin/dogtag.py:512
msgid ""
"DSA keys should not have a passphrase in the database, for being used "
"during retrieval."
msgstr ""

#: barbican/plugin/dogtag.py:516
msgid ""
"Secrets of type {secret_type} should not have a passphrase in the "
"database, for being used during retrieval."
msgstr ""

#: barbican/plugin/dogtag.py:530
msgid ""
"Encryption using session key is not supported when retrieving a "
"{secret_type} key."
msgstr ""

#: barbican/plugin/dogtag.py:559
msgid "Exception thrown by enroll_cert: {message}"
msgstr ""

#: barbican/plugin/dogtag.py:589
msgid "{request} not found for {operation} for order_id {order_id}"
msgstr ""

#: barbican/plugin/dogtag.py:628
msgid "No request found for request_id {request_id} for order {order_id}"
msgstr ""

#: barbican/plugin/dogtag.py:654
msgid ""
"Request {request_id} reports status_complete, but no cert_id has been "
"returned"
msgstr ""

#: barbican/plugin/dogtag.py:665
msgid "Certificate not found for cert_id: {cert_id}"
msgstr ""

#: barbican/plugin/dogtag.py:675
msgid "Invalid request_status returned by CA"
msgstr ""

#: barbican/plugin/dogtag.py:780
msgid "No profile_id specified"
msgstr ""

#: barbican/plugin/dogtag.py:801
msgid "No request returned in enrollment_results"
msgstr ""

#: barbican/plugin/dogtag.py:819
msgid "request_id {req_id} returns COMPLETE but no cert returned"
msgstr ""

#: barbican/plugin/dogtag.py:823
msgid "Invalid request_status {status} for request_id {request_id}"
msgstr ""

#: barbican/plugin/dogtag.py:857
msgid "Modify request: unable to cancel: {message}"
msgstr ""

#: barbican/plugin/dogtag.py:886
msgid "no request found for this order"
msgstr ""

#: barbican/plugin/kmip_secret_store.py:45
msgid "The default username for authenticating with KMIP"
msgstr ""

#: barbican/plugin/kmip_secret_store.py:49
msgid "The default password for authenticating with KMIP"
msgstr ""

#: barbican/plugin/kmip_secret_store.py:53
msgid "Address of the KMIP server"
msgstr ""

#: barbican/plugin/kmip_secret_store.py:57
msgid "Port for the KMIP server"
msgstr ""

#: barbican/plugin/kmip_secret_store.py:61
msgid "SSL version, maps to the module ssl's constants"
msgstr ""

#: barbican/plugin/kmip_secret_store.py:65
msgid "File path to concatenated \"certification authority\" certificates"
msgstr ""

#: barbican/plugin/kmip_secret_store.py:70
msgid "File path to local client certificate"
msgstr ""

#: barbican/plugin/kmip_secret_store.py:74
msgid "File path to local client certificate keyfile"
msgstr ""

#: barbican/plugin/kmip_secret_store.py:190
msgid "Feature not yet implemented by KMIP Secret Store plugin"
msgstr ""

#: barbican/plugin/kmip_secret_store.py:290
msgid ""
"Unknown key value type received from KMIP server, expected "
"{key_value_struct} or {key_value_string}, received: {key_value_type}"
msgstr ""

#: barbican/plugin/kmip_secret_store.py:509
msgid "Status: {status}, Reason: {reason}, Message: {message}"
msgstr ""

#: barbican/plugin/kmip_secret_store.py:533
msgid "Bad key file permissions found, expected 400 for path: {file_path}"
msgstr ""

#: barbican/plugin/symantec.py:34
msgid "Symantec username for authentication"
msgstr ""

#: barbican/plugin/symantec.py:36
msgid "Symantec password for authentication"
msgstr ""

#: barbican/plugin/symantec.py:38
msgid "Domain of Symantec API"
msgstr ""

#: barbican/plugin/symantec.py:54
msgid "username is required"
msgstr ""

#: barbican/plugin/symantec.py:57
msgid "password is required"
msgstr ""

#: barbican/plugin/symantec.py:60
msgid "url is required"
msgstr ""

#: barbican/plugin/crypto/crypto.py:27
msgid "Crypto plugin not found."
msgstr ""

#: barbican/plugin/crypto/crypto.py:32
#: barbican/plugin/interface/certificate_manager.py:134
#: barbican/plugin/interface/certificate_manager.py:148
#: barbican/plugin/interface/certificate_manager.py:162
#: barbican/plugin/interface/secret_store.py:124
msgid "Unknown"
msgstr ""

#: barbican/plugin/crypto/crypto.py:34
msgid "Failed to bind kek metadata for plugin: {name}"
msgstr ""

#: barbican/plugin/crypto/crypto.py:44
msgid "Could not generate private key"
msgstr ""

#: barbican/plugin/crypto/manager.py:35
#: barbican/plugin/interface/certificate_manager.py:45
#: barbican/plugin/interface/secret_store.py:36
msgid "Extension namespace to search for plugins."
msgstr ""

#: barbican/plugin/crypto/manager.py:39
msgid "List of crypto plugins to load."
msgstr ""

#: barbican/plugin/crypto/p11_crypto.py:138
msgid "Path to vendor PKCS11 library"
msgstr ""

#: barbican/plugin/crypto/p11_crypto.py:140
msgid "Password to login to PKCS11 session"
msgstr ""

#: barbican/plugin/crypto/p11_crypto.py:142
msgid "Master KEK label (used in the HSM)"
msgstr ""

#: barbican/plugin/crypto/p11_crypto.py:144
msgid "Master KEK length in bytes."
msgstr ""

#: barbican/plugin/crypto/p11_crypto.py:146
msgid "HMAC label (used in the HSM)"
msgstr ""

#: barbican/plugin/crypto/p11_crypto.py:236
msgid "More than one key found for label"
msgstr ""

#: barbican/plugin/crypto/p11_crypto.py:240
msgid "General exception"
msgstr ""

#: barbican/plugin/crypto/p11_crypto.py:261
msgid "library_path is required"
msgstr ""

#: barbican/plugin/crypto/p11_crypto.py:654
msgid "Feature not implemented for PKCS11"
msgstr ""

#: barbican/plugin/crypto/simple_crypto.py:33
msgid "Key encryption key to be used by Simple Crypto Plugin"
msgstr ""

#: barbican/plugin/crypto/simple_crypto.py:48
msgid "KEK not yet created."
msgstr ""

#: barbican/plugin/crypto/simple_crypto.py:62
msgid "Unencrypted data must be a byte type, but was {unencrypted_type}"
msgstr ""

#: barbican/plugin/crypto/simple_crypto.py:132
msgid "Passphrase not supported for DSA key"
msgstr ""

#: barbican/plugin/interface/certificate_manager.py:49
#: barbican/plugin/interface/certificate_manager.py:69
msgid "List of certificate plugins to load."
msgstr ""

#: barbican/plugin/interface/certificate_manager.py:65
msgid "Extension namespace to search for eventing plugins."
msgstr ""

#: barbican/plugin/interface/certificate_manager.py:102
msgid "Certificate plugin \"{name}\" not found."
msgstr ""

#: barbican/plugin/interface/certificate_manager.py:106
msgid "Certificate plugin not found or configured."
msgstr ""

#: barbican/plugin/interface/certificate_manager.py:114
msgid "Certificate event plugin \"{name}\" not found."
msgstr ""

#: barbican/plugin/interface/certificate_manager.py:118
msgid "Certificate event plugin not found."
msgstr ""

#: barbican/plugin/interface/certificate_manager.py:126
msgid "Certificate status of {status} not supported"
msgstr ""

#: barbican/plugin/interface/certificate_manager.py:136
msgid "Problem seen during certificate processing - Reason: {reason}"
msgstr ""

#: barbican/plugin/interface/certificate_manager.py:150
msgid "Problem with data in certificate request - Reason: {reason}"
msgstr ""

#: barbican/plugin/interface/certificate_manager.py:164
msgid "Invalid operation requested - Reason: {reason}"
msgstr ""

#: barbican/plugin/interface/secret_store.py:40
msgid "List of secret store plugins to load."
msgstr ""

#: barbican/plugin/interface/secret_store.py:50
msgid "No plugin was found that could support your request"
msgstr ""

#: barbican/plugin/interface/secret_store.py:55
msgid "Secret store plugin \"{name}\" not found."
msgstr ""

#: barbican/plugin/interface/secret_store.py:58
msgid "Secret store plugin not found."
msgstr ""

#: barbican/plugin/interface/secret_store.py:64
msgid "Secret store plugin not found for requested operation."
msgstr ""

#: barbican/plugin/interface/secret_store.py:74
msgid "A Content-Type of '{content_type}' for secrets is not supported"
msgstr ""

#: barbican/plugin/interface/secret_store.py:79
msgid "content-type of '{content_type}' not supported"
msgstr ""

#: barbican/plugin/interface/secret_store.py:91
msgid "Secret Content-Encoding of '{content_encoding}' not supported"
msgstr ""

#: barbican/plugin/interface/secret_store.py:96
msgid "content-encoding of '{content_encoding}' not supported"
msgstr ""

#: barbican/plugin/interface/secret_store.py:105
msgid "No secret information provided to encrypt."
msgstr ""

#: barbican/plugin/interface/secret_store.py:112
msgid ""
"Text-based binary secret payloads must specify a content-encoding of "
"'base64'"
msgstr ""

#: barbican/plugin/interface/secret_store.py:118
msgid "Encoding type must be 'base64' for text-based payloads."
msgstr ""

#: barbican/plugin/interface/secret_store.py:126
msgid "Problem seen during crypto processing - Reason: {reason}"
msgstr ""

#: barbican/plugin/interface/secret_store.py:135
#: barbican/plugin/interface/secret_store.py:140
msgid "Problem decoding payload"
msgstr ""

#: barbican/plugin/interface/secret_store.py:148
msgid "Secret Accept of '{accept}' not supported"
msgstr ""

#: barbican/plugin/interface/secret_store.py:157
msgid "Not Found. Sorry but your secret is in another castle"
msgstr ""

#: barbican/plugin/interface/secret_store.py:163
msgid "No secret information found"
msgstr ""

#: barbican/plugin/interface/secret_store.py:169
msgid "Requested algorithm is not supported"
msgstr ""

#: barbican/plugin/interface/secret_store.py:174
msgid "Secret algorithm of '{algorithm}' not supported"
msgstr ""

#: barbican/plugin/interface/secret_store.py:184
msgid "No secret store plugins have been configured"
msgstr ""

#: barbican/plugin/interface/secret_store.py:189
#, python-format
msgid ""
"The requested Store Plugin %(plugin_name) is not currently available. "
"This is probably a server misconfiguration."
msgstr ""

#: barbican/queue/__init__.py:36
msgid "True enables queuing, False invokes workers synchronously"
msgstr ""

#: barbican/queue/__init__.py:39
msgid "Queue namespace"
msgstr ""

#: barbican/queue/__init__.py:41
msgid "Queue topic name"
msgstr ""

#: barbican/queue/__init__.py:43
msgid "Version of tasks invoked via queue"
msgstr ""

#: barbican/queue/__init__.py:45
msgid "Server name for RPC task processing server"
msgstr ""

#: barbican/queue/__init__.py:56
msgid "True enables keystone notification listener  functionality."
msgstr ""

#: barbican/queue/__init__.py:59
msgid ""
"The default exchange under which topics are scoped. May be overridden by "
"an exchange name specified in  the transport_url option."
msgstr ""

#: barbican/queue/__init__.py:63
msgid ""
"Keystone notification queue topic name. This name needs to match one of "
"values mentioned in Keystone deployment's 'notification_topics' "
"configuration e.g.    notification_topics=notifications,     "
"barbican_notificationsMultiple servers may listen on a topic and messages"
"  will be dispatched to one of the servers in a round-robin fashion. "
"That's why Barbican service  should have its own dedicated notification "
"queue so  that it receives all of Keystone notifications."
msgstr ""

#: barbican/queue/__init__.py:75
msgid ""
"True enables requeue feature in case of notification processing error. "
"Enable this only when underlying transport supports this feature."
msgstr ""

#: barbican/queue/__init__.py:79
msgid "Version of tasks invoked via notifications"
msgstr ""

#: barbican/queue/__init__.py:81
msgid ""
"Define the number of max threads to be used for notification server "
"processing functionality."
msgstr ""

#: barbican/tasks/keystone_consumer.py:36
msgid "Project cleanup via Keystone notifications"
msgstr ""

#: barbican/tasks/resources.py:149
msgid "Process TypeOrder"
msgstr ""

#: barbican/tasks/resources.py:243 barbican/tasks/resources.py:305
msgid "Order type \"{order_type}\" not implemented."
msgstr ""

#: barbican/tasks/resources.py:250
msgid "Update Order"
msgstr ""

#: barbican/tests/tasks/test_resources.py:147
#: barbican/tests/tasks/test_resources.py:297
msgid "Process TypeOrder failure seen - please contact site administrator."
msgstr ""

#: barbican/tests/tasks/test_resources.py:224
msgid "Update Order failure seen - please contact site administrator."
msgstr ""

