# Translations template for barbican.
# Copyright (C) 2015 ORGANIZATION
# This file is distributed under the same license as the barbican project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2015.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: barbican 2015.1.dev83\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2015-02-01 06:10+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"

#: barbican/api/__init__.py:64
msgid "Read Error"
msgstr ""

#: barbican/api/__init__.py:74
msgid "Malformed JSON"
msgstr ""

#: barbican/api/__init__.py:114
msgid ""
"{operation} attempt not allowed - please review your user/project "
"privileges"
msgstr ""

#: barbican/api/__init__.py:121
msgid "content-type of '{content_type}' not supported"
msgstr ""

#: barbican/api/__init__.py:125
msgid "content-encoding of '{content_encoding}' not supported"
msgstr ""

#: barbican/api/__init__.py:129
msgid "No plugin was found that could support your request"
msgstr ""

#: barbican/api/__init__.py:133 barbican/plugin/interface/secret_store.py:115
msgid "Problem decoding payload"
msgstr ""

#: barbican/api/__init__.py:136
msgid ""
"Text-based binary secret payloads must specify a content-encoding of "
"'base64'"
msgstr ""

#: barbican/api/__init__.py:140
msgid "Not Found.  Sorry but your secret is in another castle"
msgstr ""

#: barbican/api/__init__.py:144
msgid "Requested algorithm is not supported"
msgstr ""

#: barbican/api/__init__.py:156
msgid "No information provided to process"
msgstr ""

#: barbican/api/__init__.py:159
msgid "Provided information too large to process"
msgstr ""

#: barbican/api/__init__.py:164
msgid "{operation} failure seen - please contact site administrator."
msgstr ""

#: barbican/api/__init__.py:168
msgid "{operation} issue seen - {reason}."
msgstr ""

#: barbican/api/controllers/__init__.py:88
msgid "System"
msgstr ""

#: barbican/api/controllers/__init__.py:120
msgid "Unexpected content type: {type}.  Expected content types are: {expected}"
msgstr ""

#: barbican/api/controllers/consumers.py:31
msgid "Not Found. Sorry but your consumer is in another castle."
msgstr ""

#: barbican/api/controllers/consumers.py:49
msgid "ContainerConsumer retrieval"
msgstr ""

#: barbican/api/controllers/consumers.py:87
msgid "ContainerConsumers(s) retrieval"
msgstr ""

#: barbican/api/controllers/consumers.py:126
msgid "ContainerConsumer creation"
msgstr ""

#: barbican/api/controllers/consumers.py:155
msgid "ContainerConsumer deletion"
msgstr ""

#: barbican/api/controllers/containers.py:32
msgid "Not Found. Sorry but your container is in another castle."
msgstr ""

#: barbican/api/controllers/containers.py:56
msgid "Container retrieval"
msgstr ""

#: barbican/api/controllers/containers.py:76
msgid "Container deletion"
msgstr ""

#: barbican/api/controllers/containers.py:123
msgid "Containers(s) retrieval"
msgstr ""

#: barbican/api/controllers/containers.py:161
msgid "Container creation"
msgstr ""

#: barbican/api/controllers/containers.py:186
msgid "Secret provided for '{secret_name}' doesn't exist."
msgstr ""

#: barbican/api/controllers/orders.py:32
msgid "Not Found. Sorry but your order is in another castle."
msgstr ""

#: barbican/api/controllers/orders.py:38
msgid "Secret metadata expected but not received."
msgstr ""

#: barbican/api/controllers/orders.py:43
msgid "Order update is not supported."
msgstr ""

#: barbican/api/controllers/orders.py:48
msgid "Updates are not supported for order type {0}."
msgstr ""

#: barbican/api/controllers/orders.py:54
msgid "Only PENDING orders can be updated. Order is in the{0} state."
msgstr ""

#: barbican/api/controllers/orders.py:60
msgid "Cannot modify order type."
msgstr ""

#: barbican/api/controllers/orders.py:79
msgid "Order retrieval"
msgstr ""

#: barbican/api/controllers/orders.py:91 barbican/api/controllers/orders.py:185
msgid "Order update"
msgstr ""

#: barbican/api/controllers/orders.py:124
msgid "Order deletion"
msgstr ""

#: barbican/api/controllers/orders.py:158
msgid "Order(s) retrieval"
msgstr ""

#: barbican/api/controllers/orders.py:191
msgid "Order creation"
msgstr ""

#: barbican/api/controllers/secrets.py:44
msgid "Not Found. Sorry but your secret is in another castle."
msgstr ""

#: barbican/api/controllers/secrets.py:50
msgid "Secret already has data, cannot modify it."
msgstr ""

#: barbican/api/controllers/secrets.py:59
msgid ""
"Transport key wrapped session key has been provided to wrap secrets for "
"retrieval, but the transport key id has not been provided."
msgstr ""

#: barbican/api/controllers/secrets.py:89
msgid "Secret retrieval"
msgstr ""

#: barbican/api/controllers/secrets.py:137
msgid "Secret update"
msgstr ""

#: barbican/api/controllers/secrets.py:147
msgid "Content-Type of '{content_type}' is not supported for PUT."
msgstr ""

#: barbican/api/controllers/secrets.py:181
msgid "Secret deletion"
msgstr ""

#: barbican/api/controllers/secrets.py:227
msgid "Secret(s) retrieval"
msgstr ""

#: barbican/api/controllers/secrets.py:278
msgid "Secret creation"
msgstr ""

#: barbican/api/controllers/transportkeys.py:34
msgid "Not Found. Transport Key not found."
msgstr ""

#: barbican/api/controllers/transportkeys.py:50
msgid "Transport Key retrieval"
msgstr ""

#: barbican/api/controllers/transportkeys.py:62
msgid "Transport Key deletion"
msgstr ""

#: barbican/api/controllers/transportkeys.py:94
msgid "Transport Key(s) retrieval"
msgstr ""

#: barbican/api/controllers/transportkeys.py:129
msgid "Transport Key Creation"
msgstr ""

#: barbican/api/controllers/versions.py:33
msgid "Version retrieval"
msgstr ""

#: barbican/api/middleware/context.py:30
msgid ""
"When true, this option sets the owner of an image to be the project. "
"Otherwise, the owner of the  image will be the authenticated user issuing"
" the request."
msgstr ""

#: barbican/api/middleware/context.py:35
msgid "Role used to identify an authenticated user as administrator."
msgstr ""

#: barbican/api/middleware/context.py:38
msgid ""
"Allow unauthenticated users to access the API with read-only privileges. "
"This only applies when using ContextMiddleware."
msgstr ""

#: barbican/api/middleware/context.py:117
msgid "Problem processing X-Service-Catalog"
msgstr ""

#: barbican/api/middleware/context.py:142
msgid "Missing X-Project-Id"
msgstr ""

#: barbican/common/exception.py:39
msgid "An unknown exception occurred"
msgstr ""

#: barbican/common/exception.py:56
msgid "Missing required argument."
msgstr ""

#: barbican/common/exception.py:60
#, python-format
msgid "Missing required credential: %(required)s"
msgstr ""

#: barbican/common/exception.py:64
#, python-format
msgid "Missing required metadata field for %(required)s"
msgstr ""

#: barbican/common/exception.py:68
msgid "Invalid subject DN: %(subject_dn)"
msgstr ""

#: barbican/common/exception.py:72
msgid "Invalid container: %(reason)"
msgstr ""

#: barbican/common/exception.py:76
msgid "Invalid extensions data."
msgstr ""

#: barbican/common/exception.py:80
msgid "Invalid CMC Data"
msgstr ""

#: barbican/common/exception.py:84
msgid "Invalid PKCS10 Data"
msgstr ""

#: barbican/common/exception.py:88
msgid "Invalid Certificate Request Type"
msgstr ""

#: barbican/common/exception.py:92
#, python-format
msgid ""
"Incorrect auth strategy, expected \"%(expected)s\" but received "
"\"%(received)s\""
msgstr ""

#: barbican/common/exception.py:97
msgid "An object with the specified identifier was not found."
msgstr ""

#: barbican/common/exception.py:101
#, python-format
msgid "Unknown scheme '%(scheme)s' found in URI"
msgstr ""

#: barbican/common/exception.py:105
msgid "The Store URI was malformed."
msgstr ""

#: barbican/common/exception.py:109
msgid "An object with the same identifier already exists."
msgstr ""

#: barbican/common/exception.py:113
msgid "There is not enough disk space on the image storage media."
msgstr ""

#: barbican/common/exception.py:117
msgid "Permission to write image storage media denied."
msgstr ""

#: barbican/common/exception.py:121
#, python-format
msgid "Connect error/bad request to Auth service at URL %(url)s."
msgstr ""

#: barbican/common/exception.py:125
#, python-format
msgid "Auth service at URL %(url)s not found."
msgstr ""

#: barbican/common/exception.py:129
msgid "Authorization failed."
msgstr ""

#: barbican/common/exception.py:133
msgid "You are not authenticated."
msgstr ""

#: barbican/common/exception.py:137 barbican/common/exception.py:145
#: barbican/common/exception.py:154
msgid "You are not authorized to complete this action."
msgstr ""

#: barbican/common/exception.py:141
msgid "Operation is not supported."
msgstr ""

#: barbican/common/exception.py:149
#, python-format
msgid "Image %(image_id)s is protected and cannot be deleted."
msgstr ""

#: barbican/common/exception.py:158
msgid "Data supplied was not valid."
msgstr ""

#: barbican/common/exception.py:162
msgid "No data supplied to process."
msgstr ""

#: barbican/common/exception.py:166
msgid "Sort key supplied was not valid."
msgstr ""

#: barbican/common/exception.py:170
msgid "Unable to filter using the specified range."
msgstr ""

#: barbican/common/exception.py:174
#, python-format
msgid "Attribute '%(property)s' is read-only."
msgstr ""

#: barbican/common/exception.py:178
#, python-format
msgid "Attribute '%(property)s' is reserved."
msgstr ""

#: barbican/common/exception.py:182
#, python-format
msgid "Redirecting to %(uri)s for authorization."
msgstr ""

#: barbican/common/exception.py:186
msgid "There was an error migrating the database."
msgstr ""

#: barbican/common/exception.py:190
msgid "There was an error connecting to a server"
msgstr ""

#: barbican/common/exception.py:194
msgid "There was an error configuring the client."
msgstr ""

#: barbican/common/exception.py:198
#, python-format
msgid ""
"The request returned a 302 Multiple Choices. This generally means that "
"you have not included a version indicator in a request URI.\n"
"\n"
"The body of response returned:\n"
"%(body)s"
msgstr ""

#: barbican/common/exception.py:205
#, python-format
msgid ""
"The request returned a 413 Request Entity Too Large. This generally means"
" that rate limiting or a quota threshold was breached.\n"
"\n"
"The response body:\n"
"%(body)s"
msgstr ""

#: barbican/common/exception.py:216
msgid ""
"The request returned 503 Service Unavilable. This generally occurs on "
"service overload or other transient outage."
msgstr ""

#: barbican/common/exception.py:227
msgid "The request returned 500 Internal Server Error."
msgstr ""

#: barbican/common/exception.py:231
#, python-format
msgid ""
"The request returned an unexpected status: %(status)s.\n"
"\n"
"The response body:\n"
"%(body)s"
msgstr ""

#: barbican/common/exception.py:236
#, python-format
msgid "Invalid content type %(content_type)s"
msgstr ""

#: barbican/common/exception.py:240
#, python-format
msgid "Invalid content encoding %(content_encoding)s"
msgstr ""

#: barbican/common/exception.py:244
msgid "Error while attempting to decode payload."
msgstr ""

#: barbican/common/exception.py:248
#, python-format
msgid "Registry was not configured correctly on API server. Reason: %(reason)s"
msgstr ""

#: barbican/common/exception.py:253
#, python-format
msgid "Store %(store_name)s could not be configured correctly. Reason: %(reason)s"
msgstr ""

#: barbican/common/exception.py:258
#, python-format
msgid ""
"Driver %(driver_name)s could not be configured correctly. Reason: "
"%(reason)s"
msgstr ""

#: barbican/common/exception.py:263
msgid "Deleting images from this store is not supported."
msgstr ""

#: barbican/common/exception.py:267
msgid "Configuration for store failed. Adding images to this store is disabled."
msgstr ""

#: barbican/common/exception.py:272
#, python-format
msgid "'%(strategy)s' is not an available notifier strategy."
msgstr ""

#: barbican/common/exception.py:276
#, python-format
msgid "Maximum redirects (%(redirects)s) was exceeded."
msgstr ""

#: barbican/common/exception.py:280
msgid "Received invalid HTTP redirect."
msgstr ""

#: barbican/common/exception.py:284
msgid "Response from Keystone does not contain a Barbican endpoint."
msgstr ""

#: barbican/common/exception.py:289
#, python-format
msgid ""
"Multiple 'image' service matches for region %(region)s. This generally "
"means that a region is required and you have not supplied one."
msgstr ""

#: barbican/common/exception.py:295
#, python-format
msgid "Server worker creation failed: %(reason)s."
msgstr ""

#: barbican/common/exception.py:299
#, python-format
msgid "Unable to load schema: %(reason)s"
msgstr ""

#: barbican/common/exception.py:303
#, python-format
msgid "Provided object does not match schema '%(schema)s': %(reason)s"
msgstr ""

#: barbican/common/exception.py:312
#, python-format
msgid ""
"No support for value set on field '%(field)s' on schema '%(schema)s': "
"%(reason)s"
msgstr ""

#: barbican/common/exception.py:321
#, python-format
msgid ""
"Feature not implemented for value set on field '%(field)s' on schema "
"'%(schema)s': %(reason)s"
msgstr ""

#: barbican/common/exception.py:330
#, python-format
msgid "Provided header feature is unsupported: %(feature)s"
msgstr ""

#: barbican/common/exception.py:334
msgid ""
"The image cannot be deleted because it is in use through the backend "
"store outside of Barbican."
msgstr ""

#: barbican/common/exception.py:339
msgid "The provided image is too large."
msgstr ""

#: barbican/common/utils.py:113
msgid "Cannot generate a fullname for a null instance"
msgstr ""

#: barbican/common/validators.py:82
msgid "{schema_name}' within '{parent_schema_name}"
msgstr ""

#: barbican/common/validators.py:166
msgid "If 'payload' specified, must be non empty"
msgstr ""

#: barbican/common/validators.py:172
msgid "payload must be provided when payload_content_type is specified"
msgstr ""

#: barbican/common/validators.py:201 barbican/common/validators.py:473
msgid "Invalid date for 'expiration'"
msgstr ""

#: barbican/common/validators.py:215
msgid "'expiration' is before current time"
msgstr ""

#: barbican/common/validators.py:228
msgid "If 'payload' is supplied, 'payload_content_type' must also be supplied."
msgstr ""

#: barbican/common/validators.py:239
msgid ""
"payload_content_encoding must be specified when payload_content_type is "
"application/octet-stream."
msgstr ""

#: barbican/common/validators.py:247
msgid ""
"payload_content_encoding must not be specified when payload_content_type "
"is text/plain"
msgstr ""

#: barbican/common/validators.py:256
msgid "payload_content_type is not one of {supported}"
msgstr ""

#: barbican/common/validators.py:320
msgid "'payload' not allowed for key type order"
msgstr ""

#: barbican/common/validators.py:339
msgid "Only 'application/octet-stream' supported"
msgstr ""

#: barbican/common/validators.py:345
msgid "'algorithm' is required field for asymmetric type order"
msgstr ""

#: barbican/common/validators.py:485
msgid "Must have non-zero positive bit_length to generate secret"
msgstr ""

#: barbican/common/validators.py:493
msgid "Must be a positive integer that is a multiple of 8"
msgstr ""

#: barbican/common/validators.py:501
msgid "Feature not implemented for '{0}' order type"
msgstr ""

#: barbican/common/validators.py:573
msgid "Duplicate reference names are not allowed"
msgstr ""

#: barbican/common/validators.py:585
msgid "Duplicate secret ids are not allowed"
msgstr ""

#: barbican/common/validators.py:603
msgid ""
"only 'private_key', 'public_key' and 'private_key_passphrase' reference "
"names are allowed for RSA type"
msgstr ""

#: barbican/common/validators.py:611
msgid ""
"The minimum required reference names are 'public_key' and'private_key' "
"for RSA type"
msgstr ""

#: barbican/common/validators.py:624
msgid ""
"only 'private_key', 'certificate' , 'private_key_passphrase',  or "
"'intermediates' reference names are allowed for Certificate type"
msgstr ""

#: barbican/common/validators.py:632
msgid "The minimum required reference name is 'certificate' for Certificate type"
msgstr ""

#: barbican/common/validators.py:678
msgid "plugin_name must be provided"
msgstr ""

#: barbican/common/validators.py:685
msgid "transport_key must be provided"
msgstr ""

#: barbican/model/models.py:743
msgid "Must supply Non-None {0} argument for CertificateAuthority entry."
msgstr ""

#: barbican/model/models.py:809
msgid "Must supply non-None {0} argument for CertificateAuthorityMetadatum entry."
msgstr ""

#: barbican/model/models.py:854
msgid "Must supply non-None {0} argument for ProjectCertificateAuthority entry."
msgstr ""

#: barbican/model/models.py:901
msgid "Must supply non-None {0} argument for PreferredCertificateAuthority entry."
msgstr ""

#: barbican/model/repositories.py:168
msgid "No SQL connection configured"
msgstr ""

#: barbican/model/repositories.py:182
msgid ""
"Error configuring registry database with supplied sql_connection. Got "
"error: {error}"
msgstr ""

#: barbican/model/repositories.py:410
msgid "Must supply non-None {entity_name}."
msgstr ""

#: barbican/model/repositories.py:416
msgid "Must supply {entity_name} with id=None (i.e. new entity)."
msgstr ""

#: barbican/model/repositories.py:494
msgid "{entity_name} status is required."
msgstr ""

#: barbican/model/repositories.py:499
msgid "Invalid status '{status}' for {entity_name}."
msgstr ""

#: barbican/model/repositories.py:519
msgid "{entity_name} is missing query build method for get project entities."
msgstr ""

#: barbican/model/repositories.py:571
#, python-format
msgid "Error deleting project entities for project_id=%s"
msgstr ""

#: barbican/model/repositories.py:603
msgid "No {entity_name} found with keystone-ID {id}"
msgstr ""

#: barbican/model/repositories.py:797
msgid "Tried to register crypto plugin with null or empty name."
msgstr ""

#: barbican/model/repositories.py:1135
msgid "Could not find {entity_name}"
msgstr ""

#: barbican/model/repositories.py:1269
msgid "No {entity} found with ID {id}"
msgstr ""

#: barbican/model/repositories.py:1275
msgid "Entity ID {entity_id} not found"
msgstr ""

#: barbican/model/repositories.py:1281
msgid "No entities of type {entity_name} found"
msgstr ""

#: barbican/model/repositories.py:1287
msgid "Entity '{entity_name}' already exists"
msgstr ""

#: barbican/openstack/common/eventlet_backdoor.py:142
#, python-format
msgid "Eventlet backdoor listening on %(port)s for process %(pid)d"
msgstr ""

#: barbican/openstack/common/gettextutils.py:305
msgid "Message objects do not support addition."
msgstr ""

#: barbican/openstack/common/gettextutils.py:315
msgid ""
"Message objects do not support str() because they may contain non-ascii "
"characters. Please use unicode() or translate() instead."
msgstr ""

#: barbican/openstack/common/log.py:327
#, python-format
msgid "Deprecated: %s"
msgstr ""

#: barbican/openstack/common/log.py:438
#, python-format
msgid "Error loading logging config %(log_config)s: %(err_msg)s"
msgstr ""

#: barbican/openstack/common/log.py:489
#, python-format
msgid "syslog facility must be one of: %s"
msgstr ""

#: barbican/openstack/common/log.py:722
#, python-format
msgid "Fatal call to deprecated config: %(msg)s"
msgstr ""

#: barbican/openstack/common/loopingcall.py:84
#, python-format
msgid "task run outlasted interval by %s sec"
msgstr ""

#: barbican/openstack/common/loopingcall.py:91
msgid "in fixed duration looping call"
msgstr ""

#: barbican/openstack/common/loopingcall.py:131
#, python-format
msgid "Dynamic looping call sleeping for %.02f seconds"
msgstr ""

#: barbican/openstack/common/loopingcall.py:138
msgid "in dynamic looping call"
msgstr ""

#: barbican/openstack/common/policy.py:96
msgid "The JSON file that defines policies."
msgstr ""

#: barbican/openstack/common/policy.py:99
msgid "Default rule. Enforced when a requested rule is not found."
msgstr ""

#: barbican/openstack/common/policy.py:114
#, python-format
msgid "Policy doesn't allow %s to be performed."
msgstr ""

#: barbican/openstack/common/policy.py:208
#, python-format
msgid "Rules must be an instance of dict or Rules, got %s instead"
msgstr ""

#: barbican/openstack/common/processutils.py:90
#, python-format
msgid "Got unknown keyword args to utils.execute: %r"
msgstr ""

#: barbican/openstack/common/processutils.py:99
#, python-format
msgid "Running cmd (subprocess): %s"
msgstr ""

#: barbican/openstack/common/processutils.py:114
#, python-format
msgid "Result was %s"
msgstr ""

#: barbican/openstack/common/processutils.py:128
#, python-format
msgid "%r failed. Retrying."
msgstr ""

#: barbican/openstack/common/service.py:118
#: barbican/openstack/common/service.py:335
msgid "Full set of CONF:"
msgstr ""

#: barbican/openstack/common/service.py:127
#: barbican/openstack/common/service.py:217
#, python-format
msgid "Caught %s, exiting"
msgstr ""

#: barbican/openstack/common/service.py:139
msgid "Exception during rpc cleanup."
msgstr ""

#: barbican/openstack/common/service.py:188
msgid "Parent process has died unexpectedly, exiting"
msgstr ""

#: barbican/openstack/common/service.py:223
msgid "Unhandled exception"
msgstr ""

#: barbican/openstack/common/service.py:256
msgid "Forking too fast, sleeping"
msgstr ""

#: barbican/openstack/common/service.py:278
#, python-format
msgid "Started child %d"
msgstr ""

#: barbican/openstack/common/service.py:288
#, python-format
msgid "Starting %d workers"
msgstr ""

#: barbican/openstack/common/service.py:305
#, python-format
msgid "Child %(pid)d killed by signal %(sig)d"
msgstr ""

#: barbican/openstack/common/service.py:309
#, python-format
msgid "Child %(pid)s exited with status %(code)d"
msgstr ""

#: barbican/openstack/common/service.py:313
#, python-format
msgid "pid %d not in child list"
msgstr ""

#: barbican/openstack/common/service.py:345
#, python-format
msgid "Caught %s, stopping children"
msgstr ""

#: barbican/openstack/common/service.py:363
#, python-format
msgid "Waiting on %d children to exit"
msgstr ""

#: barbican/openstack/common/sslutils.py:52
#, python-format
msgid "Unable to find cert_file : %s"
msgstr ""

#: barbican/openstack/common/sslutils.py:55
#, python-format
msgid "Unable to find ca_file : %s"
msgstr ""

#: barbican/openstack/common/sslutils.py:58
#, python-format
msgid "Unable to find key_file : %s"
msgstr ""

#: barbican/openstack/common/sslutils.py:61
msgid ""
"When running server in SSL mode, you must specify both a cert_file and "
"key_file option value in your configuration file"
msgstr ""

#: barbican/openstack/common/sslutils.py:100
#, python-format
msgid "Invalid SSL version : %s"
msgstr ""

#: barbican/openstack/common/strutils.py:92
#, python-format
msgid "Unrecognized value '%(val)s', acceptable values are: %(acceptable)s"
msgstr ""

#: barbican/openstack/common/strutils.py:197
#, python-format
msgid "Invalid unit system: \"%s\""
msgstr ""

#: barbican/openstack/common/strutils.py:206
#, python-format
msgid "Invalid string format: %s"
msgstr ""

#: barbican/openstack/common/crypto/utils.py:29
msgid "An unknown error occurred in crypto utils."
msgstr ""

#: barbican/openstack/common/crypto/utils.py:36
#, python-format
msgid "Block size of %(given)d is too big, max = %(maximum)d"
msgstr ""

#: barbican/openstack/common/crypto/utils.py:45
#, python-format
msgid "Length of %(given)d is too long, max = %(maximum)d"
msgstr ""

#: barbican/plugin/dogtag.py:44
msgid "Path to PEM file for authentication"
msgstr ""

#: barbican/plugin/dogtag.py:47
msgid "Hostname for the Dogtag instance"
msgstr ""

#: barbican/plugin/dogtag.py:50
msgid "Port for the Dogtag instance"
msgstr ""

#: barbican/plugin/dogtag.py:52
msgid "Path to the NSS certificate database"
msgstr ""

#: barbican/plugin/dogtag.py:54
msgid "Password for NSS certificate database"
msgstr ""

#: barbican/plugin/dogtag.py:68
msgid "nss_password is required"
msgstr ""

#: barbican/plugin/dogtag.py:83
msgid "pem_path is required"
msgstr ""

#: barbican/plugin/dogtag.py:94
msgid "Invalid algorithm passed in"
msgstr ""

#: barbican/plugin/dogtag.py:98
msgid "Operation not supported by Dogtag Plugin"
msgstr ""

#: barbican/plugin/dogtag.py:357
msgid ""
"Passphrase encryption is not supported for symmetric key generating "
"algorithms."
msgstr ""

#: barbican/plugin/dogtag.py:389
msgid "Passphrase encryption is not supported for DSA algorithm"
msgstr ""

#: barbican/plugin/dogtag.py:510
msgid ""
"DSA keys should not have a passphrase in the database, for being used "
"during retrieval."
msgstr ""

#: barbican/plugin/dogtag.py:514
msgid ""
"Secrets of type {secret_type} should not have a passphrase in the "
"database, for being used during retrieval."
msgstr ""

#: barbican/plugin/dogtag.py:528
msgid ""
"Encryption using session key is not supported when retrieving a "
"{secret_type} key."
msgstr ""

#: barbican/plugin/dogtag.py:569
msgid "{request} not found for {operation} for order_id {order_id}"
msgstr ""

#: barbican/plugin/dogtag.py:608
msgid "No request found for request_id {request_id} for order {order_id}"
msgstr ""

#: barbican/plugin/dogtag.py:634
msgid ""
"Request {request_id} reports status_complete, but no cert_id has been "
"returned"
msgstr ""

#: barbican/plugin/dogtag.py:645
msgid "Certificate not found for cert_id: {cert_id}"
msgstr ""

#: barbican/plugin/dogtag.py:655
msgid "Invalid request_status returned by CA"
msgstr ""

#: barbican/plugin/dogtag.py:680
msgid "No profile_id specified"
msgstr ""

#: barbican/plugin/dogtag.py:694
msgid "No request returned in enrollment_results"
msgstr ""

#: barbican/plugin/dogtag.py:714
msgid "request_id {req_id} returns COMPLETE but no cert returned"
msgstr ""

#: barbican/plugin/dogtag.py:718
msgid "Invalid request_status {status} for request_id {request_id}"
msgstr ""

#: barbican/plugin/dogtag.py:738
msgid "Exception thrown by enroll_cert: {message}"
msgstr ""

#: barbican/plugin/dogtag.py:764
msgid "Modify request: unable to cancel: {message}"
msgstr ""

#: barbican/plugin/dogtag.py:793
msgid "no request found for this order"
msgstr ""

#: barbican/plugin/kmip_secret_store.py:47
msgid "The default username for authenticating with KMIP"
msgstr ""

#: barbican/plugin/kmip_secret_store.py:51
msgid "The default password for authenticating with KMIP"
msgstr ""

#: barbican/plugin/kmip_secret_store.py:55
msgid "Address of the KMIP server"
msgstr ""

#: barbican/plugin/kmip_secret_store.py:59
msgid "Port for the KMIP server"
msgstr ""

#: barbican/plugin/kmip_secret_store.py:63
msgid "SSL version, maps to the module ssl's constants"
msgstr ""

#: barbican/plugin/kmip_secret_store.py:67
msgid "File path to concatenated \"certification authority\" certificates"
msgstr ""

#: barbican/plugin/kmip_secret_store.py:72
msgid "File path to local client certificate"
msgstr ""

#: barbican/plugin/kmip_secret_store.py:76
msgid "File path to local client certificate keyfile"
msgstr ""

#: barbican/plugin/kmip_secret_store.py:192
msgid "Feature not yet implemented by KMIP Secret Store plugin"
msgstr ""

#: barbican/plugin/kmip_secret_store.py:292
msgid ""
"Unknown key value type received from KMIP server, expected "
"{key_value_struct} or {key_value_string}, received: {key_value_type}"
msgstr ""

#: barbican/plugin/kmip_secret_store.py:511
msgid "Status: {status}, Reason: {reason}, Message: {message}"
msgstr ""

#: barbican/plugin/kmip_secret_store.py:535
msgid "Bad key file permissions found, expected 400 for path: {file_path}"
msgstr ""

#: barbican/plugin/symantec.py:34
msgid "Symantec username for authentication"
msgstr ""

#: barbican/plugin/symantec.py:36
msgid "Symantec password for authentication"
msgstr ""

#: barbican/plugin/symantec.py:38
msgid "Domain of Symantec API"
msgstr ""

#: barbican/plugin/symantec.py:54
msgid "username is required"
msgstr ""

#: barbican/plugin/symantec.py:57
msgid "password is required"
msgstr ""

#: barbican/plugin/symantec.py:60
msgid "url is required"
msgstr ""

#: barbican/plugin/crypto/crypto.py:27
msgid "Crypto plugin not found."
msgstr ""

#: barbican/plugin/crypto/crypto.py:32
#: barbican/plugin/interface/certificate_manager.py:134
#: barbican/plugin/interface/certificate_manager.py:144
#: barbican/plugin/interface/certificate_manager.py:154
#: barbican/plugin/interface/secret_store.py:103
msgid "Unknown"
msgstr ""

#: barbican/plugin/crypto/crypto.py:34
msgid "Failed to bind kek metadata for plugin: {name}"
msgstr ""

#: barbican/plugin/crypto/crypto.py:44
msgid "Could not generate private key"
msgstr ""

#: barbican/plugin/crypto/manager.py:35
#: barbican/plugin/interface/certificate_manager.py:45
#: barbican/plugin/interface/secret_store.py:36
msgid "Extension namespace to search for plugins."
msgstr ""

#: barbican/plugin/crypto/manager.py:39
msgid "List of crypto plugins to load."
msgstr ""

#: barbican/plugin/crypto/p11_crypto.py:136
msgid "Path to vendor PKCS11 library"
msgstr ""

#: barbican/plugin/crypto/p11_crypto.py:138
msgid "Password to login to PKCS11 session"
msgstr ""

#: barbican/plugin/crypto/p11_crypto.py:140
msgid "Master KEK label (used in the HSM)"
msgstr ""

#: barbican/plugin/crypto/p11_crypto.py:142
msgid "Master KEK length in bytes."
msgstr ""

#: barbican/plugin/crypto/p11_crypto.py:144
msgid "HMAC label (used in the HSM)"
msgstr ""

#: barbican/plugin/crypto/p11_crypto.py:234
msgid "More than one key found for label"
msgstr ""

#: barbican/plugin/crypto/p11_crypto.py:238
msgid "General exception"
msgstr ""

#: barbican/plugin/crypto/p11_crypto.py:259
msgid "library_path is required"
msgstr ""

#: barbican/plugin/crypto/p11_crypto.py:652
msgid "Feature not implemented for PKCS11"
msgstr ""

#: barbican/plugin/crypto/simple_crypto.py:33
msgid "Key encryption key to be used by Simple Crypto Plugin"
msgstr ""

#: barbican/plugin/crypto/simple_crypto.py:48
msgid "KEK not yet created."
msgstr ""

#: barbican/plugin/crypto/simple_crypto.py:62
msgid "Unencrypted data must be a byte type, but was {unencrypted_type}"
msgstr ""

#: barbican/plugin/crypto/simple_crypto.py:132
msgid "Passphrase not supported for DSA key"
msgstr ""

#: barbican/plugin/interface/certificate_manager.py:49
#: barbican/plugin/interface/certificate_manager.py:69
msgid "List of certificate plugins to load."
msgstr ""

#: barbican/plugin/interface/certificate_manager.py:65
msgid "Extension namespace to search for eventing plugins."
msgstr ""

#: barbican/plugin/interface/certificate_manager.py:102
msgid "Certificate plugin \"{name}\" not found."
msgstr ""

#: barbican/plugin/interface/certificate_manager.py:106
msgid "Certificate plugin not found or configured."
msgstr ""

#: barbican/plugin/interface/certificate_manager.py:114
msgid "Certificate event plugin \"{name}\" not found."
msgstr ""

#: barbican/plugin/interface/certificate_manager.py:118
msgid "Certificate event plugin not found."
msgstr ""

#: barbican/plugin/interface/certificate_manager.py:126
msgid "Certificate status of {status} not supported"
msgstr ""

#: barbican/plugin/interface/certificate_manager.py:136
msgid "Problem seen during certificate processing - Reason: {reason}"
msgstr ""

#: barbican/plugin/interface/certificate_manager.py:146
msgid "Problem with data in certificate request - Reason: {reason}"
msgstr ""

#: barbican/plugin/interface/certificate_manager.py:156
msgid "Invalid operation requested - Reason: {reason}"
msgstr ""

#: barbican/plugin/interface/secret_store.py:40
msgid "List of secret store plugins to load."
msgstr ""

#: barbican/plugin/interface/secret_store.py:51
msgid "Secret store plugin \"{name}\" not found."
msgstr ""

#: barbican/plugin/interface/secret_store.py:54
msgid "Secret store plugin not found."
msgstr ""

#: barbican/plugin/interface/secret_store.py:60
msgid "Secret store plugin not found for requested operation."
msgstr ""

#: barbican/plugin/interface/secret_store.py:67
msgid "A Content-Type of '{content_type}' for secrets is not supported"
msgstr ""

#: barbican/plugin/interface/secret_store.py:78
msgid "Secret Content-Encoding of '{content_encoding}' not supported"
msgstr ""

#: barbican/plugin/interface/secret_store.py:89
msgid "No secret information provided to encrypt."
msgstr ""

#: barbican/plugin/interface/secret_store.py:97
msgid "Encoding type must be 'base64' for text-based payloads."
msgstr ""

#: barbican/plugin/interface/secret_store.py:105
msgid "Problem seen during crypto processing - Reason: {reason}"
msgstr ""

#: barbican/plugin/interface/secret_store.py:123
msgid "Secret Accept of '{accept}' not supported"
msgstr ""

#: barbican/plugin/interface/secret_store.py:133
msgid "No secret information found"
msgstr ""

#: barbican/plugin/interface/secret_store.py:141
msgid "Secret algorithm of '{algorithm}' not supported"
msgstr ""

#: barbican/plugin/interface/secret_store.py:151
msgid "No secret store plugins have been configured"
msgstr ""

#: barbican/queue/__init__.py:36
msgid "True enables queuing, False invokes workers synchronously"
msgstr ""

#: barbican/queue/__init__.py:39
msgid "Queue namespace"
msgstr ""

#: barbican/queue/__init__.py:41
msgid "Queue topic name"
msgstr ""

#: barbican/queue/__init__.py:43
msgid "Version of tasks invoked via queue"
msgstr ""

#: barbican/queue/__init__.py:45
msgid "Server name for RPC task processing server"
msgstr ""

#: barbican/queue/__init__.py:56
msgid "True enables keystone notification listener  functionality."
msgstr ""

#: barbican/queue/__init__.py:59
msgid ""
"The default exchange under which topics are scoped. May be overridden by "
"an exchange name specified in  the transport_url option."
msgstr ""

#: barbican/queue/__init__.py:63
msgid ""
"Keystone notification queue topic name. This name needs to match one of "
"values mentioned in Keystone deployment's 'notification_topics' "
"configuration e.g.    notification_topics=notifications,     "
"barbican_notificationsMultiple servers may listen on a topic and messages"
"  will be dispatched to one of the servers in a round-robin fashion. "
"That's why Barbican service  should have its own dedicated notification "
"queue so  that it receives all of Keystone notifications."
msgstr ""

#: barbican/queue/__init__.py:75
msgid ""
"True enables requeue feature in case of notification processing error. "
"Enable this only when underlying transport supports this feature."
msgstr ""

#: barbican/queue/__init__.py:79
msgid "Version of tasks invoked via notifications"
msgstr ""

#: barbican/queue/__init__.py:81
msgid ""
"Define the number of max threads to be used for notification server "
"processing functionality."
msgstr ""

#: barbican/tasks/keystone_consumer.py:36
msgid "Project cleanup via Keystone notifications"
msgstr ""

#: barbican/tasks/resources.py:149
msgid "Process TypeOrder"
msgstr ""

#: barbican/tasks/resources.py:243 barbican/tasks/resources.py:305
msgid "Order type \"{order_type}\" not implemented."
msgstr ""

#: barbican/tasks/resources.py:250
msgid "Update Order"
msgstr ""

#: barbican/tests/tasks/test_resources.py:147
#: barbican/tests/tasks/test_resources.py:297
msgid "Process TypeOrder failure seen - please contact site administrator."
msgstr ""

#: barbican/tests/tasks/test_resources.py:224
msgid "Update Order failure seen - please contact site administrator."
msgstr ""

